// script.aculo.us slider.js v1.8.3, Thu Oct 08 11:23:33 +0200 2009
// Copyright (c) 2005-2009 Marty Haught, Thomas Fuchs
// script.aculo.us is freely distributable under the terms of an MIT-style license.
if(!Control)var Control={};var slider={};
Control.Slider=Class.create({initialize:function(b,a,c){slider=this;this.flag=!1;this.handles=Object.isArray(b)?b.collect(function(a){return $(a)}):[$(b)];this.track=$(a);this.options=c||{};this.axis=this.options.axis||"horizontal";this.increment=this.options.increment||1;this.step=parseInt(this.options.step||"1");this.range=this.options.range||$R(0,1);this.value=0;this.values=this.handles.map(function(){return 0});this.spans=this.options.spans?this.options.spans.map(function(a){return $(a)}):!1;
this.options.startSpan=$(this.options.startSpan||null);this.options.endSpan=$(this.options.endSpan||null);this.restricted=this.options.restricted||!1;this.maximum=this.options.maximum||this.range.end;this.minimum=this.options.minimum||this.range.start;this.alignX=parseInt(this.options.alignX||"0");this.alignY=parseInt(this.options.alignY||"0");this.trackLength=this.maximumOffset()-this.minimumOffset();this.handleLength=this.isVertical()?0!=this.handles[0].offsetHeight?this.handles[0].offsetHeight:
this.handles[0].style.height.replace(/px$/,""):0!=this.handles[0].offsetWidth?this.handles[0].offsetWidth:this.handles[0].style.width.replace(/px$/,"");this.disabled=this.dragging=this.active=!1;this.options.disabled&&this.setDisabled();if(this.allowedValues=this.options.values?this.options.values.sortBy(Prototype.K):!1)this.minimum=this.allowedValues.min(),this.maximum=this.allowedValues.max();this.eventMouseDown=this.startDrag.bindAsEventListener(this);this.eventMouseUp=this.endDrag.bindAsEventListener(this);
this.eventMouseMove=this.update.bindAsEventListener(this);this.handles.each(function(a,b){b=slider.handles.length-1-b;slider.setValue(parseFloat((Object.isArray(slider.options.sliderValue)?slider.options.sliderValue[b]:slider.options.sliderValue)||slider.range.start),b);a.makePositioned().observe("mousedown",slider.eventMouseDown)});this.track.observe("mousedown",this.eventMouseDown);document.observe("mouseup",this.eventMouseUp);document.observe("mousemove",this.eventMouseMove);this.initialized=!0},
dispose:function(){var b=this;Event.stopObserving(this.track,"mousedown",this.eventMouseDown);Event.stopObserving(document,"mouseup",this.eventMouseUp);Event.stopObserving(document,"mousemove",this.eventMouseMove);this.handles.each(function(a){Event.stopObserving(a,"mousedown",b.eventMouseDown)})},setDisabled:function(){this.disabled=!0},setEnabled:function(){this.disabled=!1},getNearestValue:function(b){if(this.allowedValues){if(b>=this.allowedValues.max())return this.allowedValues.max();if(b<=this.allowedValues.min())return this.allowedValues.min();
var a=Math.abs(this.allowedValues[0]-b),c=this.allowedValues[0];this.allowedValues.each(function(d){var e=Math.abs(d-b);e<=a&&(c=d,a=e)});return c}return b>this.range.end?this.range.end:b<this.range.start?this.range.start:b},setValue:function(b,a){this.active||(this.activeHandleIdx=a||0,this.activeHandle=this.handles[this.activeHandleIdx],this.updateStyles());a=a||this.activeHandleIdx||0;this.initialized&&this.restricted&&(0<a&&b<this.values[a-1]&&(b=this.values[a-1]),a<this.handles.length-1&&b>this.values[a+
1]&&(b=this.values[a+1]));b=this.getNearestValue(b);this.values[a]=b;this.value=this.values[0];this.handles[a].style[this.isVertical()?"top":"left"]=this.translateToPx(b);this.drawSpans();(!this.dragging||!this.event)&&this.updateFinished()},setValueBy:function(b,a){this.setValue(this.values[a||this.activeHandleIdx||0]+b,a||this.activeHandleIdx||0)},translateToPx:function(b){return Math.round((this.trackLength-this.handleLength)/(this.range.end-this.range.start)*(b-this.range.start))+"px"},translateToValue:function(b){return b/
(this.trackLength-this.handleLength)*(this.range.end-this.range.start)+this.range.start},getRange:function(b){var a=this.values.sortBy(Prototype.K);b=b||0;return $R(a[b],a[b+1])},minimumOffset:function(){return this.isVertical()?this.alignY:this.alignX},maximumOffset:function(){return this.isVertical()?(0!=this.track.offsetHeight?this.track.offsetHeight:this.track.style.height.replace(/px$/,""))-this.alignY:(0!=this.track.offsetWidth?this.track.offsetWidth:this.track.style.width.replace(/px$/,""))-
this.alignX},isVertical:function(){return"vertical"==this.axis},drawSpans:function(){var b=this;this.spans&&$R(0,this.spans.length-1).each(function(a){b.setSpan(b.spans[a],b.getRange(a))});this.options.startSpan&&this.setSpan(this.options.startSpan,$R(0,1<this.values.length?this.getRange(0).min():this.value));this.options.endSpan&&this.setSpan(this.options.endSpan,$R(1<this.values.length?this.getRange(this.spans.length-1).max():this.value,this.maximum))},setSpan:function(b,a){this.isVertical()?(b.style.top=
this.translateToPx(a.start),b.style.height=this.translateToPx(a.end-a.start+this.range.start)):(b.style.left=this.translateToPx(a.start),b.style.width=this.translateToPx(a.end-a.start+this.range.start))},updateStyles:function(){this.handles.each(function(b){Element.removeClassName(b,"selected")});Element.addClassName(this.activeHandle,"selected")},startDrag:function(b){if(Event.isLeftClick(b)){if(!this.disabled){this.active=!0;var a=Event.element(b),c=[Event.pointerX(b),Event.pointerY(b)];if(a==this.track)a=
this.track.cumulativeOffset(),this.event=b,this.setValue(this.translateToValue((this.isVertical()?c[1]-a[1]:c[0]-a[0])-this.handleLength/2)),a=this.activeHandle.cumulativeOffset(),this.offsetX=c[0]-a[0],this.offsetY=c[1]-a[1];else{for(;-1==this.handles.indexOf(a)&&a.parentNode;)a=a.parentNode;-1!=this.handles.indexOf(a)&&(this.activeHandle=a,this.activeHandleIdx=this.handles.indexOf(this.activeHandle),this.updateStyles(),a=this.activeHandle.cumulativeOffset(),this.offsetX=c[0]-a[0],this.offsetY=c[1]-
a[1])}}Event.stop(b)}},update:function(b){this.active&&(this.dragging||(this.dragging=!0),this.draw(b),Prototype.Browser.WebKit&&window.scrollBy(0,0),Event.stop(b))},draw:function(b){var a=[Event.pointerX(b),Event.pointerY(b)],c=this.track.cumulativeOffset();a[0]-=this.offsetX+c[0];a[1]-=this.offsetY+c[1];this.event=b;this.setValue(this.translateToValue(this.isVertical()?a[1]:a[0]));if(this.initialized&&this.options.onSlide)this.options.onSlide(1<this.values.length?this.values:this.value,this)},endDrag:function(b){this.flag=
!1;this.active&&this.dragging&&(this.finishDrag(b,!0),Event.stop(b));this.dragging=this.active=!1},finishDrag:function(){this.dragging=this.active=!1;this.updateFinished()},updateFinished:function(){if(this.initialized&&this.options.onChange)this.options.onChange(1<this.values.length?this.values:this.value,this);this.event=null;this.flag||this.sliderange()},sliderange:function(){this.flag=!0;var b=0;this.values[0]>this.values[1]&&(this.values[0]=this.values[1]-this.step,b=1);if(b){this.options.sliderValue=
[this.values[0],this.values[1]];var a=this;this.handles.each(function(b,d){d=a.handles.length-1-d;a.setValue(parseFloat((Object.isArray(a.options.sliderValue)?a.options.sliderValue[d]:a.options.sliderValue)||a.range.start),d);b.makePositioned().observe("mousedown",a.eventMouseDown)})}},reset:function(){this.handles.each(function(b,a){a=slider.handles.length-1-a;slider.setValue(parseFloat((Object.isArray(slider.options.sliderValue)?slider.options.sliderValue[a]:slider.options.sliderValue)||slider.range.start),
a);b.makePositioned().observe("mousedown",slider.eventMouseDown)})}});